// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2iFdAn3UT5PztzpR-7t0A3dSKbZE1ZrM',
    appId: '1:409319135381:web:a5022a92778507e9a7e39c',
    messagingSenderId: '409319135381',
    projectId: 'cloudproject-53dc6',
    authDomain: 'cloudproject-53dc6.firebaseapp.com',
    storageBucket: 'cloudproject-53dc6.appspot.com',
    measurementId: 'G-5XC4QWZKRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnWYnu1OlgfvINEJ2LAbbVHz5FIx5398c',
    appId: '1:409319135381:android:7722f429efedc5b0a7e39c',
    messagingSenderId: '409319135381',
    projectId: 'cloudproject-53dc6',
    storageBucket: 'cloudproject-53dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvShzyS_8lsdpdoC-HWAXGnsp8rvOrnJc',
    appId: '1:409319135381:ios:d603816ea2f43ea0a7e39c',
    messagingSenderId: '409319135381',
    projectId: 'cloudproject-53dc6',
    storageBucket: 'cloudproject-53dc6.appspot.com',
    iosClientId: '409319135381-37afs6brg9dg7mls0pkmhn10kamsra1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvShzyS_8lsdpdoC-HWAXGnsp8rvOrnJc',
    appId: '1:409319135381:ios:d603816ea2f43ea0a7e39c',
    messagingSenderId: '409319135381',
    projectId: 'cloudproject-53dc6',
    storageBucket: 'cloudproject-53dc6.appspot.com',
    iosClientId: '409319135381-37afs6brg9dg7mls0pkmhn10kamsra1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxArchitecture',
  );
}
